language: scala
cache:
  directories:
    - $HOME/.ivy2/cache
scala:
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - sbt csimJVM/test
  - sbt csimJVM/compile
  - sbt csimJVM/package
  - sbt csimJS/fullOptJS
